### ISSUE TITLE
work on animations and UI

### ISSUE THREAD

**Issue by adyasha9** [adyasha9/piano#1]
Add button press and release animation and any modification to UI can be done to make it look better. Please provide screenshots for better reviewing.

**Comment by haseeb1009** [comment]
@adyasha9  What animation do you want on the UI can you please add some more details?

**Comment by adyasha9** [comment]
@haseeb1009 I updated the description box

**Comment by haseeb1009** [comment]
you can assign this issue to me

**Comment by adyasha9** [comment]
@haseeb1009 go ahead
